### ISSUE TITLE
dark mode query table background color

### ISSUE THREAD

**Issue by dale502** [rcvd/logseq-bear-theme#11]
dark mode don't have separate table line background color
![image](https://user-images.githubusercontent.com/69394230/143387430-efac6398-b62f-46be-aeae-6785ede438eb.png)
light mode has
![image](https://user-images.githubusercontent.com/69394230/143387463-250aa2aa-028c-49cb-8f1b-28240c2cd4b1.png)

**Comment by dale502** [comment]
simply table as well
![image](https://user-images.githubusercontent.com/69394230/143387847-58403033-a778-4f5d-8524-85f30b5b9588.png)
![image](https://user-images.githubusercontent.com/69394230/143387874-632baf85-14e5-4e8a-a3e8-2b2eada16012.png)

**Comment by FirasSadiyah** [comment]
Thans for the nice theme. Advanced query, i.e. `#+BEGIN_QUERY` also don't show line stripes.
