### ISSUE TITLE
light mode parent tag in linked ref issue

### ISSUE THREAD

**Issue by dale502** [rcvd/logseq-bear-theme#2]
![image](https://user-images.githubusercontent.com/69394230/142788156-9d4a4dee-c99c-4cb8-a1a2-e489caed893a.png)
![image](https://user-images.githubusercontent.com/69394230/142788136-210308bd-4f2a-434b-9da5-28493880803b.png)

**Comment by rcvd** [comment]
Fixed with latest updated
