### ISSUE TITLE
two lines between blocks for logseq 0.5.6 (win)

### ISSUE THREAD

**Issue by chempeng** [rcvd/logseq-bear-theme#20]
When logseq is updated to version 0.5.6 (win), two lines will appear between the blocks. 
![image](https://user-images.githubusercontent.com/24810120/147730685-ea6654c6-40ce-45e2-bce8-ea98c354f717.png)

**Comment by substa** [comment]
I confirm the issue, present also on Mac Os

**Comment by rcvd** [comment]
Should be fixed with latest update
