### ISSUE TITLE
font selection

### ISSUE THREAD

**Issue by mkosma** [rcvd/logseq-bear-theme#24]
Is there an easy way I can adapt this theme to use a different font?

**Comment by Jack-KkKk** [comment]
I really want to know this!

**Comment by rcvd** [comment]
You can use my Excel-based [CSS generator](https://github.com/rcvd/logseq-css-system) if you are brave. Haven't found the time yet to create good documentation, but it's fully working.

Still thinking about a more comfortable way but Logseq doesn't allow easy custom CSS blocks like Roam Research does.
