### ISSUE TITLE
Blue rectangles in latest version of logseq

### ISSUE THREAD

**Issue by m1karii** [rcvd/logseq-bear-theme#26]
Just updated logseq desktop to 6.7 and there are blue rectangles appearing on the end of each line which has link in it
![image](https://user-images.githubusercontent.com/82673417/166108874-0d20eb64-a310-4977-96f4-a5f58e991a36.png)

**Comment by m1karii** [comment]
I noticed another thing I don't think is intended. When I have some page or block opened in the right sidebar the icon for new bullet at the bottom of the page/bullet is shown all the time. This isn't the case in the main part of the window where it appears only on hover-over.
![image](https://user-images.githubusercontent.com/82673417/166136182-90c64c70-c1fb-488c-8c96-c5ff66516be2.png)

**Comment by m1karii** [comment]
Aaand another thing I don't think is intended...
links to pages have square brackets greyish in color (as seen in image below)
![image](https://user-images.githubusercontent.com/82673417/166462176-4fc8ae87-5db4-454c-ada3-13af111e23f4.png)
where links to PDFs have square brackets blue in color (as seen in image below)
![image](https://user-images.githubusercontent.com/82673417/166295392-890157b0-18f6-4f58-91ce-612256d50636.png)
page links also get highlited on hover, where PDF links don't

**Comment by rcvd** [comment]
It isn't fixed yet, still looking for a solution.

**Comment by rcvd** [comment]
I hope the first issue is fixed now - please check...

**Comment by m1karii** [comment]
yes, the first issue is solved

I did a bit of thinking on the third one and I don't think its an issue anymore as this is how it is in default logseq theme and all other themes I have installed

**Comment by rcvd** [comment]
The second issue should be fixed with the latest release
