### ISSUE TITLE
Formatting buttons all black in iOS

### ISSUE THREAD

**Issue by nichodges** [rcvd/logseq-bear-theme#28]
The various formatting buttons (indent, outdent, etc.) that appear above the keyboard are all blacked out in iOS. This happens in both dark and light mode.
![IMG_E30EF262F69A-1](https://user-images.githubusercontent.com/1241176/166324819-17f7757b-6f5a-43b2-945b-bcf4a7d50f6e.jpeg)

**Comment by happybit** [comment]
same problem here

**Comment by rcvd** [comment]
Should be fixed with the latest update

**Comment by happybit** [comment]
> Should be fixed with the latest update

thanks. it works now 😁
