### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by m1karii** [rcvd/logseq-bear-theme#29]
Please support code blocks with this theme. Code blocks are enclosed in three backticks `` ``` ``
![image](https://user-images.githubusercontent.com/82673417/167478034-ee8b1fca-d664-4140-95a7-dcd4bdc594b1.png)
this is how it looks now:
![image](https://user-images.githubusercontent.com/82673417/167478096-48d2ce5b-e086-4c42-b75e-e62e33b3cad7.png)

**Comment by rcvd** [comment]
Should be fixed now
