### ISSUE TITLE
Dark mode in Plugins view issue 

### ISSUE THREAD

**Issue by sawhney17** [rcvd/logseq-bear-theme#3]
<img width="1440" alt="Screen Shot 2021-11-22 at 6 19 02 AM" src="https://user-images.githubusercontent.com/80150109/142791493-da28631d-edbf-4789-adf2-d153442f53aa.png">
Looks like there are some areas across the board slight missing colors and all. Lovely theme though!

**Comment by danieltomasz** [comment]
Great theme! 
There is the same issue in theme switcher in bear dark theme

**Comment by rcvd** [comment]
Fixed with latest updated
