### ISSUE TITLE
Bullets are moving around on hover-over

### ISSUE THREAD

**Issue by m1karii** [rcvd/logseq-bear-theme#30]

**Comment by rcvd** [comment]
Can you show the problem? I'm not seeing any movement of the bullets, just a slight zoom in and a border on hover.

**Comment by m1karii** [comment]
sorry I didn't investigate further before posting this issue; it only happens if the line contains a header: begins with `#` or `##` etc.

**Comment by rcvd** [comment]
Are you using the bullet threading plugin?

**Comment by m1karii** [comment]
no

**Comment by m1karii** [comment]
closing this issue as the problem seems to have been resolved
