### ISSUE TITLE
Buttons in the top bar not visible

### ISSUE THREAD

**Issue by sebastianfastert** [rcvd/logseq-bear-theme#31]
Hi,

for example the search button does not look how it is supposed to. See Screenshot
<img width="747" alt="image" src="https://user-images.githubusercontent.com/17435627/174658919-644fe152-7e01-4de5-8fcd-80309209ea5b.png">

And the fonts in the left menu are also not easily readable.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/17435627/174659021-492e9137-658b-4644-85e5-4cd12d2275f8.png">

Thanks a lot!

**Comment by andtheweb** [comment]
Came here to report the same issues, only to find that you beat me to it. Cheers.

**Comment by rcvd** [comment]
Should be fixed now. Please report if you still find something after a refresh.
