### ISSUE TITLE
Link to settings missing

### ISSUE THREAD

**Issue by ituri** [rcvd/logseq-bear-theme#4]
I'm running 0.4.9 with no other CSS snippets added to my custom.css. The link to access the settings is missing from the three dot menu
![Screenshot 2021-11-22 at 08 51 27](https://user-images.githubusercontent.com/871297/142823784-fa50f31a-5714-4d7b-b48d-26f6985f9021.png)
.

**Comment by rcvd** [comment]
This is a "feature" of the latest Logseq version and does not relate to the bear theme.

**Comment by ituri** [comment]
I've not heard of it before. Can you tell me how to enter the settings in this latest release?

**Comment by rcvd** [comment]
Open an normal page (not the journal) and you find it behind the three dots.

**Comment by substa** [comment]
It's not a feature. The general settings link is currently available in menu with default theme, but it's missed if bear theme is enabled.
<img width="343" alt="screenshot2" src="https://user-images.githubusercontent.com/1065285/142934011-bf06b245-9be6-4890-afbc-bae2baa431f0.png">
<img width="384" alt="screenshot1" src="https://user-images.githubusercontent.com/1065285/142934018-5e9b5c25-6a0e-44be-9f17-6a93b15a18bc.png">
d.

**Comment by TakiGuan** [comment]
I think this is not the feature, the default them can show the setting linkage.

**Comment by rcvd** [comment]
My fault, sorry. Re-opening the issue, will be fixed today.

**Comment by rcvd** [comment]
Fixed with latest release
