### ISSUE TITLE
Plugin Toggles don't differentiate on/off

### ISSUE THREAD

**Issue by tylerwince** [rcvd/logseq-bear-theme#6]
In Logseq, you can toggle on/off plugins that you have installed. It would be nice if the color was different in the "toggled off" position (see image for one toggled on and one toggled off).

Looks like they use `aria-checked="true"` for active and `false` for inactive (see HTML below).

![image](https://user-images.githubusercontent.com/17678033/142884711-74d6b18e-5bfd-4ced-98b2-4ca466921bdb.png)

```html
<a class="ui__toggle is-small">
  <span aria-checked="true" tabindex="0" role="checkbox" class="wrapper transition-colors ease-in-out duration-200 bg-indigo-600">
    <span aria-hidden="true" class="switcher transform transition ease-in-out duration-200 translate-x-4">
    </span>
  </span>
</a>
```

**Comment by rcvd** [comment]
Fixed with latest updated
