### ISSUE TITLE
dark mode cards review background color

### ISSUE THREAD

**Issue by dale502** [rcvd/logseq-bear-theme#7]
![image](https://user-images.githubusercontent.com/69394230/142971690-59dd9216-72d4-4e07-b378-96feb45caffd.png)
![image](https://user-images.githubusercontent.com/69394230/142971661-24767f2b-95de-4f5c-a428-ad72dd48756a.png)
light mode is fine
![image](https://user-images.githubusercontent.com/69394230/142971741-a5ce670a-ceb5-40cc-b177-23fd5cfb518b.png)

**Comment by rcvd** [comment]
Fixed with latest release

**Comment by dale502** [comment]
this issue is back again in the latest update
