### ISSUE TITLE
Journal queries not styled

### ISSUE THREAD

**Issue by substa** [rcvd/logseq-bear-theme#8]
Hi, 

it seems that some queries on journal pages (those configured in config.edn)  are not styled yet.
<img width="889" alt="screen2" src="https://user-images.githubusercontent.com/1065285/143016543-fb656301-1667-4353-8e0a-1fba1d88477e.png">
<img width="842" alt="screen1" src="https://user-images.githubusercontent.com/1065285/143016548-b0f0eebf-14b1-4e55-a4ac-783d50c5cce1.png">

**Comment by rcvd** [comment]
Not sure how you get this "Next" Item. Have you changed something in the config? How does your Nov 23rd, 2021 page look like?

**Comment by substa** [comment]
> Not sure how you get this "Next" Item. Have you changed something in the config? How does your Nov 23rd, 2021 page look like?

No, it's one of the default queries in config.edn:
``` {:title      "📅 NEXT"
    :query      [:find (pull ?h [*])
                 :in $ ?start ?next
                 :where
                 [?h :block/marker ?marker]
                 [(contains? #{"NOW" "LATER" "TODO"} ?marker)]
                 [?h :block/ref-pages ?p]
                 [?p :block/journal? true]
                 [?p :block/journal-day ?d]
                 [(> ?d ?start)]
                 [(< ?d ?next)]]
    :inputs     [:today :7d-after]
    :collapsed? false}]}
```
    
It shows the tasks with future date backlinks
    
I think the class of the block to style is **.custom-query**

**Comment by rcvd** [comment]
Should be fixed now
